### ISSUE TITLE
Docker does not like at all such a big port range as -p 49152-65535

### ISSUE THREAD

**Issue by douardda** [AVENTER-UG/docker-matrix#12]
unless I missed something, on my setup, the "docker run -p 49152-65535:49152-65535 ", as decribed in the Example.configs doc file, takes ages, since docker insert one pair of iptable rules for each port.

I'm using docker-ce 18.03 on a debian stretch host, and dockerd is ruinning with the --userland-proxy=false option.

Is there a know trick for this?

**Comment by mvgorcum** [comment]
Yes, you can decrease the coturn portrange in turnserver.conf (also described in the example):

```
min-port=XXXX
max-port=XXXX
```
Then you can also only expose that portrange in docker.

**Comment by douardda** [comment]
I've seen that, but I wonder if the example used in the documentation can actually work. Is there some magic docker config flag to set? 

If so, it might be useful to add some warning about this problem and give some hints.

**Comment by mvgorcum** [comment]
That's valid criticism. I've actually never really looked at it, since I didn't want to expose the whole port range anyway.

A bit of searching brought me [this](https://success.docker.com/article/docker-compose-and-docker-run-hang-when-binding-a-large-port-range), which may help if you want to keep using the whole port range for coturn.

When I have some time I'll add a comment about this in the example config.

**Comment by andreaspeters** [comment]
@mvgorcum was so nice and fix it. :-) thanks.

**Comment by douardda** [comment]
thanks @mvgorcum
