### ISSUE TITLE
LD_PRELOAD env variable

### ISSUE THREAD

**Issue by skylord123** [AVENTER-UG/docker-matrix#19]
Is it possible to use the LD_PRELOAD env variable to help with RAM usage? Well, I know it possible. I mean for this container.

Here is the description from the readme:
https://github.com/matrix-org/synapse/blob/master/README.rst#id46

Looks like it requires the libjemalloc1 library and a pointer to it. I'm not sure it is included in this docker container or where it would be located.

Btw: thanks for the great container.

**Comment by mvgorcum** [comment]
It is possible for the container as well. I have been experimenting with it in a few branches on my fork. [this](https://github.com/mvgorcum/docker-matrix/tree/jemalloc2) one should work fine (though I don't currently use it).

What can also help is running under python 3. Synapse mostly supports python 3 now (since [0.33.5](https://github.com/matrix-org/synapse/releases/tag/v0.33.5)) and I made a version of this container based on python 3 [here](https://github.com/mvgorcum/docker-matrix/tree/python3), but the container is quite large, as it is on a python:3.6-stretch base. I do run this container on my personal server.
