### ISSUE TITLE
Matrix group and user are already created in docker compile

### ISSUE THREAD

**Issue by RichardRG** [AVENTER-UG/docker-matrix#49]
Hello, 

I am a bit new to docker but I am having a bit of an issue with this image on Unraid. 

I spin up the docker image with the following... (UID/GID obfuscated)

`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='matrix' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'SERVER_NAME'='matrix' -e 'REPORT_STATS'='no' -e 'SYNAPSE_CACHE_FACTOR'='0.5' -e 'MATRIX_UID'='99' -e 'MATRIX_GID'='100' -p '8008:8008/tcp' -p '8448:8448/tcp' -p '3478:3478/tcp' -p '3478:3478/udp' -v '/mnt/user/appdata/matrix/':'/data':'rw' --user 0:0 'avhost/docker-matrix:latest' start`

From what I have read on the docs this should spawn the instance using the root user and then configure the user "matrix" to 99 and the group "matrix" to 100. 

The actual result is that the docker container spins up as root and the matrix UID:GID is the default of 991:991

In reviewing the logs when it tries to run the if statement based off the $EUID == 0, it tried to create a new group with the provided GID then uses &&'s to configure the user and folders. This fails. 

I believe the issue is due to the group being created in the docker compose file and this causes the command to fail. Because the rest of the commands are based off a positive conditional AND they never run. 

I would suggest modifying them with the following lines (85-86 and 109-110). 

` groupadd -r -g $MATRIX_GID matrix || groupmod -g $MATRIX_GID matrix \`

`&& useradd -r -d /data -M -u $MATRIX_UID -g matrix matrix || usermod -u $MATRIX_UID matrix \`

There is probably a better option that I have no clue about due to my newness with docker but this is what I could figure out on my own.

**Comment by mvgorcum** [comment]
I believe that this happens because we create the matrix user (with 991:991) in the Dockerfile, causing that to be present in the image. (see [here](https://github.com/AVENTER-UG/docker-matrix/blob/4df424e2e2e000ad8e86a341a793da1378f76cae/Dockerfile#L87))

That's something we should probably fix, but for now the easiest workaround for you is to run the whole container as the user that you want synapse to be running as. That just means adding `--user 99:100` in the docker run command, and omit all the uid/gid environmental variables. That does mean you need to check that the user can read and write in the volume you map to `/data`.

As a sidenote: the 'SERVER_NAME' needs to be the synapse server name typically the root domain you're hosting your matrix server on.

**Comment by andreaspeters** [comment]
Still a issue?
